services:
  - type: web
    name: hangoutz-restaurant-server
    env: node
    buildCommand: "npm install"
    startCommand: "node src/app.js"
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
